# Generated by Django 2.1.5 on 2019-02-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_party_rehearsal_dinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='allergies',
            field=models.CharField(blank=True, choices=[('gluten-free', 'wheat'), ('nut-free', 'nuts')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('fish', 'fish'), ('chicken', 'hen'), ('vegetarian', 'vegetable')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('formal', 'formal'), ('fun', 'fun')], max_length=10),
        ),
    ]
