# Generated by Django 2.1.7 on 2019-03-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20190220_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='allergies',
        ),
        migrations.AddField(
            model_name='party',
            name='staying_onsite',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('fish', 'fish'), ('chicken', 'chicken'), ('vegetarian', 'vegetable')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='rehearsal_dinner',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('fun', 'fun')], max_length=10),
        ),
    ]
